import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppHeader, GhostButton, PrimaryButton, SectionTitle } from "@/components/mavet-ui";
import { ScreenContainer } from "@/components/screen-container";
import { exportInventoryExcel, exportInventoryPdf } from "@/lib/inventory-export";
import { currency, quantityFormat } from "@/lib/target-data";
import { useTargetStore } from "@/lib/target-store";

export default function InventoryScreen() {
  const store = useTargetStore();
  const latest = [...store.inventoryCounts].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))[0];
  const latestEntries = latest?.entries ?? [];
  const stockValue = latestEntries.reduce((sum, entry) => sum + entry.quantity * (store.products.find((product) => product.id === entry.productId)?.unitPrice ?? 0), 0);
  const exportFile = async (kind: "pdf" | "excel") => {
    if (!latest) return;
    try { if (kind === "pdf") await exportInventoryPdf(latest, store.products, store.representative); else await exportInventoryExcel(latest, store.products, store.representative); }
    catch (error) { Alert.alert("تعذر التصدير", error instanceof Error ? error.message : "حدث خطأ أثناء تصدير الجرد."); }
  };
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.scroll}><AppHeader title="جرد المخزن" subtitle="الرصيد الفعلي للمنتجات" /><PrimaryButton label="جرد جديد" onPress={() => router.push("/inventory/new" as never)} icon="playlist-add-check" /><View style={styles.addProduct}><GhostButton label="إضافة منتج للمخزن" onPress={() => router.push("/product-form")} icon="add-box" tone="gold" /></View>{!latest ? <View style={styles.empty}><MaterialIcons name="inventory-2" size={38} color="#4A1E53" /><Text style={styles.emptyTitle}>لا يوجد جرد محفوظ بعد</Text><Text style={styles.emptyDesc}>اضغط «جرد جديد» وسجّل الكمية والصلاحية والملاحظات لكل منتج خطوة بخطوة.</Text></View> : <><View style={styles.summary}><View><Text style={styles.summaryValue}>{currency(stockValue)} ج.م</Text><Text style={styles.summaryLabel}>قيمة المخزون التقديرية</Text></View><View style={styles.summaryDivider}/><View><Text style={styles.summaryValue}>{quantityFormat(latestEntries.length)}</Text><Text style={styles.summaryLabel}>منتج تم جرده</Text></View></View><View style={styles.latestHead}><View><Text style={styles.latestTitle}>{latest.title}</Text><Text style={styles.latestDate}>آخر تحديث: {latest.date}</Text></View><View style={styles.exportRow}><Pressable onPress={() => exportFile("pdf")} style={({ pressed }) => [styles.export, pressed && styles.pressed]}><MaterialIcons name="picture-as-pdf" color="#B84343" size={20}/></Pressable><Pressable onPress={() => exportFile("excel")} style={({ pressed }) => [styles.export, pressed && styles.pressed]}><MaterialIcons name="table-chart" color="#2E7D5B" size={20}/></Pressable></View></View><SectionTitle title="رصيد المنتجات" detail="حسب آخر جرد" />{store.products.map((product) => { const entry = latestEntries.find((item) => item.productId === product.id); return <View key={product.id} style={styles.item}><View style={styles.itemInfo}><Text style={styles.itemName}>{product.name}</Text><Text style={styles.itemMeta}>{product.packSize ?? "بدون عبوة محددة"}{entry?.expiryDate ? ` • صلاحية ${entry.expiryDate}` : ""}</Text>{entry?.note ? <Text style={styles.itemNote}>{entry.note}</Text> : null}</View><View style={styles.quantity}><Text style={styles.quantityValue}>{quantityFormat(entry?.quantity ?? 0)}</Text><Text style={styles.quantityLabel}>وحدة</Text></View></View>; })}</>}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ scroll: { paddingTop: 10, paddingBottom: 32 }, addProduct: { marginTop: 10, marginBottom: 14 }, empty: { alignItems: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8DFE9", borderRadius: 20, padding: 28, marginTop: 10 }, emptyTitle: { color: "#1E1522", fontSize: 17, fontWeight: "900", marginTop: 12 }, emptyDesc: { color: "#766C79", fontSize: 13, lineHeight: 20, textAlign: "center", marginTop: 6 }, summary: { flexDirection: "row-reverse", backgroundColor: "#4A1E53", borderRadius: 19, padding: 16, justifyContent: "space-around", marginTop: 3, marginBottom: 17 }, summaryValue: { color: "#FFFFFF", fontSize: 20, fontWeight: "900", textAlign: "center" }, summaryLabel: { color: "#E7D6EB", fontSize: 11, marginTop: 4, textAlign: "center" }, summaryDivider: { width: 1, backgroundColor: "rgba(255,255,255,0.2)" }, latestHead: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }, latestTitle: { color: "#1E1522", fontSize: 16, fontWeight: "900", textAlign: "right" }, latestDate: { color: "#766C79", fontSize: 12, marginTop: 3, textAlign: "right" }, exportRow: { flexDirection: "row-reverse", gap: 7 }, export: { width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8DFE9" }, pressed: { opacity: 0.7, transform: [{ scale: 0.97 }] }, item: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8DFE9", borderRadius: 16, padding: 14, marginBottom: 9 }, itemInfo: { flex: 1, alignItems: "flex-end" }, itemName: { color: "#1E1522", fontSize: 15, fontWeight: "800", textAlign: "right" }, itemMeta: { color: "#766C79", fontSize: 11, marginTop: 3, textAlign: "right" }, itemNote: { color: "#9B6211", fontSize: 11, marginTop: 4, textAlign: "right" }, quantity: { minWidth: 58, alignItems: "flex-start", marginRight: 12 }, quantityValue: { color: "#4A1E53", fontSize: 20, fontWeight: "900" }, quantityLabel: { color: "#766C79", fontSize: 10 } });
