import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, ScrollView, StyleSheet, Text, View } from "react-native";

import { AppHeader, ChoiceSheet, GhostButton, PrimaryButton, SectionTitle } from "@/components/mavet-ui";
import { useState } from "react";
import { useTargetStore } from "@/lib/target-store";
import { ScreenContainer } from "@/components/screen-container";

export default function SettingsScreen() {
  const { activeTarget, targets, setActiveTargetId, resetAll } = useTargetStore();
  const [picker, setPicker] = useState(false);
  const reset = () => Alert.alert("مسح كل البيانات؟", "سيتم حذف التارجت والعملاء والمنتجات والعمليات المخزنة على هذا الهاتف فقط. لا يمكن التراجع عن ذلك.", [{ text: "إلغاء", style: "cancel" }, { text: "مسح البيانات", style: "destructive", onPress: resetAll }]);
  return <ScreenContainer className="px-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.scroll}><AppHeader title="الإعدادات" subtitle="بياناتك محفوظة على هذا الهاتف" /><SectionTitle title="تارجت الربع" /><View style={styles.settingCard}><View style={styles.settingRow}><View style={styles.settingText}><Text style={styles.settingTitle}>{activeTarget ? `الربع ${activeTarget.quarter} • ${activeTarget.year}` : "لم يتم تحديد تارجت"}</Text><Text style={styles.settingDesc}>يمكنك الرجوع لتارجت سابق أو تعديل الربع النشط.</Text></View><View style={styles.settingIcon}><MaterialIcons name="flag" color="#4A1E53" size={20} /></View></View><View style={styles.buttonRow}><View style={styles.half}><GhostButton label="اختيار ربع" onPress={() => setPicker(true)} icon="calendar-month" /></View><View style={styles.half}><GhostButton label={activeTarget ? "تعديل التارجت" : "إعداد التارجت"} onPress={() => router.push("/target-settings")} icon="tune" tone="gold" /></View></View></View><PrimaryButton label="إضافة تارجت لربع جديد" onPress={() => router.push("/target-settings")} icon="add" /><SectionTitle title="بيانات المندوب" /><View style={styles.repCard}><View style={styles.settingText}><Text style={styles.settingTitle}>تظهر تلقائياً في رأس التقرير</Text><Text style={styles.settingDesc}>أدخل الاسم ورقم الهاتف والمنطقة ليتم تضمينها عند تصدير Excel أو PDF.</Text></View><View style={styles.repIcon}><MaterialIcons name="badge" color="#198465" size={22} /></View></View><PrimaryButton label="إعداد بيانات المندوب" onPress={() => router.push("/representative-profile")} icon="person" /><SectionTitle title="التخزين المحلي" /><View style={styles.localCard}><MaterialIcons name="phonelink-lock" color="#2E7D5B" size={26} /><View style={styles.localText}><Text style={styles.localTitle}>لا يوجد تسجيل دخول أو مزامنة</Text><Text style={styles.localDesc}>العملاء والأسعار والتارجت والعمليات تبقى على جهاز المندوب فقط حتى يتم تطوير نسخة الإدارة لاحقاً.</Text></View></View><GhostButton label="مسح جميع البيانات من الهاتف" onPress={reset} icon="delete-outline" tone="danger" /><ChoiceSheet visible={picker} title="اختيار تارجت الربع" options={targets.map((target) => ({ id: target.id, label: `الربع ${target.quarter} • ${target.year}`, caption: target.id === activeTarget?.id ? "الربع النشط" : undefined }))} onClose={() => setPicker(false)} onSelect={(id) => { setActiveTargetId(id); setPicker(false); }} emptyText="لا يوجد تارجت محفوظ. أضف تارجت جديداً أولاً." /></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ scroll: { paddingTop: 10, paddingBottom: 34 }, settingCard: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8DFE9", padding: 15, borderRadius: 18, gap: 15, marginBottom: 12 }, settingRow: { flexDirection: "row", justifyContent: "space-between", gap: 14 }, settingText: { flex: 1, alignItems: "flex-end" }, settingIcon: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#F4EDF6" }, repIcon: { width: 42, height: 42, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: "#E3F6EF" }, repCard: { flexDirection: "row", justifyContent: "space-between", gap: 14, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8DFE9", padding: 15, borderRadius: 18, marginBottom: 12 }, settingTitle: { color: "#1E1522", fontSize: 15, fontWeight: "900", textAlign: "right" }, settingDesc: { color: "#766C79", fontSize: 12, lineHeight: 18, marginTop: 4, textAlign: "right" }, buttonRow: { flexDirection: "row-reverse", gap: 9 }, half: { flex: 1 }, localCard: { flexDirection: "row-reverse", gap: 13, backgroundColor: "#F1F8F4", padding: 15, borderRadius: 17, marginBottom: 13 }, localText: { flex: 1, alignItems: "flex-end" }, localTitle: { color: "#245F45", fontSize: 14, fontWeight: "900", textAlign: "right" }, localDesc: { color: "#386A54", fontSize: 12, lineHeight: 18, marginTop: 3, textAlign: "right" } });
