import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { AppHeader, EmptyState, GhostButton, PrimaryButton, SectionTitle } from "@/components/mavet-ui";
import { currency, quantityFormat, shortDate } from "@/lib/target-data";
import { useTargetStore } from "@/lib/target-store";
import { ScreenContainer } from "@/components/screen-container";

type Activity = { id: string; kind: "sale" | "collection"; amount: number; date: string; title: string; description?: string };

export default function CustomerDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { customers, sales, collections, products, deleteCustomer, deleteSale, deleteCollection } = useTargetStore();
  const customer = customers.find((item) => item.id === id);
  const activities: Activity[] = customer ? [
    ...sales.filter((item) => item.customerId === customer.id).map((item) => ({ id: item.id, kind: "sale" as const, amount: item.total, date: item.date, title: `بيع: ${products.find((product) => product.id === item.productId)?.name ?? "منتج"}`, description: item.quantity ? `${quantityFormat(item.quantity)} وحدة` : undefined })),
    ...collections.filter((item) => item.customerId === customer.id).map((item) => ({ id: item.id, kind: "collection" as const, amount: item.amount, date: item.date, title: "تحصيل", description: item.note })),
  ].sort((a, b) => b.date.localeCompare(a.date)) : [];
  if (!customer) return <ScreenContainer className="p-5"><EmptyState icon="person-off" title="العميل غير موجود" description="ربما تم حذفه من الهاتف." /></ScreenContainer>;
  const totalSales = activities.filter((item) => item.kind === "sale").reduce((sum, item) => sum + item.amount, 0);
  const totalCollections = activities.filter((item) => item.kind === "collection").reduce((sum, item) => sum + item.amount, 0);
  const confirmDelete = () => Alert.alert("حذف العميل؟", "سيتم حذف بيانات العميل، مع بقاء العمليات السابقة ظاهرة في التارجت حتى لا تتأثر الحسابات.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => { deleteCustomer(customer.id); router.back(); } }]);
  const removeActivity = (activity: Activity) => Alert.alert("حذف العملية؟", "سيتم تحديث التارجت فوراً بعد الحذف.", [{ text: "إلغاء", style: "cancel" }, { text: "حذف", style: "destructive", onPress: () => activity.kind === "sale" ? deleteSale(activity.id) : deleteCollection(activity.id) }]);
  const header = <><AppHeader title={customer.name} subtitle={customer.note || "سجل العميل"} /><View style={styles.statRow}><View style={styles.stat}><Text style={styles.statValue}>{currency(totalSales)} ج.م</Text><Text style={styles.statLabel}>إجمالي البيع</Text></View><View style={styles.stat}><Text style={styles.statValue}>{currency(totalCollections)} ج.م</Text><Text style={styles.statLabel}>إجمالي التحصيل</Text></View></View><View style={styles.actions}><View style={styles.actionHalf}><PrimaryButton label="تحصيل" onPress={() => router.push({ pathname: "/collection", params: { customerId: customer.id } })} icon="payments" iconSide="right" /></View><View style={styles.actionHalf}><PrimaryButton label="بيع" onPress={() => router.push({ pathname: "/sale", params: { customerId: customer.id } })} icon="add-shopping-cart" iconSide="left" /></View></View><View style={styles.editRow}><GhostButton label="تعديل العميل" onPress={() => router.push({ pathname: "/customer-form", params: { id: customer.id } })} /><GhostButton label="حذف العميل" onPress={confirmDelete} icon="delete-outline" tone="danger" /></View><SectionTitle title="سجل الحركات" detail={`${quantityFormat(activities.length)} عملية`} /></>;
  return <ScreenContainer className="px-5" containerClassName="bg-background"><FlatList data={activities} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} ListHeaderComponent={header} renderItem={({ item }) => <View style={[styles.activity, item.kind === "collection" && styles.collectionActivity]}><View style={[styles.activityIcon, { backgroundColor: item.kind === "sale" ? "#FCF1DD" : "#E3F6EF" }]}><MaterialIcons name={item.kind === "sale" ? "trending-up" : "payments"} color={item.kind === "sale" ? "#C47B12" : "#198465"} size={19} /></View><View style={styles.activityText}><Text style={styles.activityTitle}>{item.title}</Text><Text style={styles.activityDate}>{shortDate(item.date)}{item.description ? ` • ${item.description}` : ""}</Text></View><View style={styles.amountBlock}><Text style={styles.amount}>{currency(item.amount)} ج.م</Text><Pressable onPress={() => removeActivity(item)} style={({ pressed }) => [styles.delete, pressed && { opacity: 0.6 }]}><MaterialIcons name="delete-outline" size={17} color="#B84343" /></Pressable></View></View>} ListEmptyComponent={<EmptyState icon="receipt-long" title="لا توجد حركات بعد" description="سجّل بيعاً أو تحصيلاً ليظهر السجل هنا." />} /></ScreenContainer>;
}

const styles = StyleSheet.create({ list: { paddingTop: 10, paddingBottom: 34 }, statRow: { flexDirection: "row-reverse", gap: 10, marginBottom: 12 }, stat: { flex: 1, backgroundColor: "#FFFFFF", borderColor: "#E8DFE9", borderWidth: 1, borderRadius: 16, padding: 13, alignItems: "flex-end" }, statValue: { color: "#4A1E53", fontWeight: "900", fontSize: 16 }, statLabel: { color: "#766C79", fontSize: 11, marginTop: 3 }, actions: { flexDirection: "row-reverse", gap: 10, marginBottom: 11 }, actionHalf: { flex: 1 }, editRow: { flexDirection: "row-reverse", gap: 9, marginBottom: 22 }, activity: { flexDirection: "row", alignItems: "center", gap: 10, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E8DFE9", padding: 12, borderRadius: 15, marginBottom: 8 }, collectionActivity: { flexDirection: "row-reverse" }, activityIcon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, activityText: { flex: 1, alignItems: "flex-end" }, activityTitle: { color: "#1E1522", fontSize: 14, fontWeight: "800", textAlign: "right" }, activityDate: { color: "#766C79", fontSize: 11, marginTop: 3, textAlign: "right" }, amountBlock: { alignItems: "flex-start", gap: 4 }, amount: { color: "#1E1522", fontSize: 12, fontWeight: "900" }, delete: { padding: 2 } });
